### ISSUE TITLE
zeta function have no method with Dual type？

### ISSUE THREAD

**Issue by afternone** [JuliaDiff/DualNumbers.jl#21]
```
x = dual(2, 1)
y = zeta(x)
```
will have a error: 'zeta' has no method matching `zeta(::Dual{Int64})`

**Comment by mlubin** [comment]
If you add the derivative rule [here](https://github.com/johnmyleswhite/Calculus.jl/blob/360624de4f8619f9266ae9b8f14d7d50c2e11f68/src/differentiate.jl#L116), it will "just work" with dual numbers. PRs accepted. Looks like ``zeta`` was mentioned in a [comment](https://github.com/johnmyleswhite/Calculus.jl/blob/360624de4f8619f9266ae9b8f14d7d50c2e11f68/src/differentiate.jl#L257) a while ago.

**Comment by afternone** [comment]
Many thanks!
