### ISSUE TITLE
Printing method calls "other" component `du`, but its accessed through `epsilon`

### ISSUE THREAD

**Issue by IainNZ** [JuliaDiff/DualNumbers.jl#24]
So is the other component the dual component, or the epsilon component?

**Comment by mlubin** [comment]
Yes

**Comment by IainNZ** [comment]
LOL

**Comment by mlubin** [comment]
I guess following https://github.com/JuliaDiff/DualNumbers.jl/pull/16, ``du`` is like ``im`` and ``epsilon`` is like ``imag``.

**Comment by IainNZ** [comment]
It looks kinda weird MO, because the overall thing is a dual number, yet, here is this `du` thing.

**Comment by mlubin** [comment]
That's a good point.
@jrevels

**Comment by jrevels** [comment]
Is it reasonable to assume that folks' terminals will generally support Unicode? It wouldn't be too difficult to change it from `du` to `ϵ`.

**Comment by IainNZ** [comment]
`\varepsilon` might be better. Certainly OSX/Linux should.

**Comment by IainNZ** [comment]
I lost track of what windows supports, technically all of unicode but maybe not by default? I think this: https://en.wikipedia.org/wiki/Code_page_850 might be default for Win 7 and earlier? @tkelman do you know?

**Comment by tkelman** [comment]
It can depend on your font settings and which terminal you run Julia under, but at least on win7 `\varepsilon` shows up okay for me in the default REPL. I forget whether my font settings would have changed what works or doesn't under cmd.

**Comment by ararslan** [comment]
This has since been changed.
