### ISSUE TITLE
Calculus.symbolic_derivative_1arg_list masking some definitions

### ISSUE THREAD

**Issue by goretkin** [JuliaDiff/DualNumbers.jl#30]
I might be confused, but 

```
julia> @which abs2(Dual(1.0,1.0))
abs2(z::DualNumbers.Dual{T<:Real}) at /Users/goretkin/.julia/v0.4/DualNumbers/src/dual.jl:186
```

https://github.com/JuliaDiff/DualNumbers.jl/blob/v0.1.5/src/dual.jl#L186
which is masking a previous definition on
https://github.com/JuliaDiff/DualNumbers.jl/blob/v0.1.5/src/dual.jl#L122

**Comment by MikaelSlevinsky** [comment]
This should be taken care of by #29.

**Comment by ScottPJones** [comment]
This still seems to be a problem, at least on v0.5 master, even with #29 merged.
I get this warning:
```julia
julia> using DualNumbers
INFO: Precompiling module DualNumbers...
WARNING: Method definition abs2(DualNumbers.Dual4) in module DualNumbers at /Users/scott/.julia/v0.5/DualNumbers/src/dual_n.jl:78 overwritten at /Users/scott/.julia/v0.5/DualNumbers/src/dual_n.jl:154.
```

**Comment by MikaelSlevinsky** [comment]
This [https://github.com/JuliaDiff/DualNumbers.jl/blob/master/src/dual.jl#L269](line) was added in dual.jl to skip `abs2`. Perhaps the same could be done in dual_n.jl
