### ISSUE TITLE
Add norm for Vector{T<:Dual}

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaDiff/DualNumbers.jl#31]
``` julia
julia> norm([dual(1.,2.),dual(3.,2.)])
ERROR: InexactError()
 in float at float.jl:121
 in generic_vecnormInf at linalg/generic.jl:92
 in generic_vecnorm2 at linalg/generic.jl:114
 in vecnorm at linalg/generic.jl:175
 in norm at linalg/generic.jl:191
```

**Comment by jrevels** [comment]
see JuliaDiff/ForwardDiff.jl#52 for prior experience with this, the key is to define `float(::Dual)`

**Comment by dlfivefifty** [comment]
I’d  expect norm(::Vector{T<:Dual}) to return a Dual.  Does this change result in that?

**Comment by jrevels** [comment]
The definition I'm thinking of is:

```julia
float(d::Dual) = Dual(float(value(d)), float(epsilon(d)))
```

With that definition, yes, `norm(::Vector{T<:Dual})` should return a `Dual`

**Comment by dlfivefifty** [comment]
OK, thanks!  Are you planning to add this definition to DualNumbers.jl?

**Comment by MikaelSlevinsky** [comment]
i thought i added this in #29? Yep, I also added a [test](https://github.com/JuliaDiff/DualNumbers.jl/blob/master/test/automatic_differentiation_test.jl#L118).

**Comment by dlfivefifty** [comment]
This has been implemented apparently.
