### ISSUE TITLE
A bug of the ^ operator

### ISSUE THREAD

**Issue by xukai92** [JuliaDiff/DualNumbers.jl#39]
Operation

`Dual(1, 0) ^ Dual(-3, 0)` 

gives error:

> DomainError:
Cannot raise an integer x to a negative power -n. 
Make x a float by adding a zero decimal (e.g. 2.0^-n instead of 2^-n), or write 1/x^n, float(x)^-n, or (x//1)^-n.
 in power_by_squaring at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in ^ at /Users/kai/.julia/v0.4/DualNumbers/src/dual.jl:235
 in include_string at /Users/kai/.julia/v0.4/CodeTools/src/eval.jl:28
 in include_string at /Users/kai/.julia/v0.4/CodeTools/src/eval.jl:32
 [inlined code] from /Users/kai/.julia/v0.4/Atom/src/eval.jl:39
 in anonymous at /Users/kai/.julia/v0.4/Atom/src/eval.jl:62
 in withpath at /Users/kai/.julia/v0.4/Requires/src/require.jl:37
 in withpath at /Users/kai/.julia/v0.4/Atom/src/eval.jl:53
 [inlined code] from /Users/kai/.julia/v0.4/Atom/src/eval.jl:61
 in anonymous at task.jl:58

Is this a bug?

**Comment by KristofferC** [comment]
No. The error message explains it. Use Floats if you want to raise to negative power.

**Comment by KristofferC** [comment]
That is `Dual(1.0, 0.0)` etc.
