### ISSUE TITLE
erf function broken in julia Nightly

### ISSUE THREAD

**Issue by rcalxrc08** [JuliaDiff/DualNumbers.jl#55]
Hi,
i am getting the following error when running some test on the latest julia nightly:
Error During Test
  Test threw an exception of type MethodError
  MethodError: no method matching erf(::DualNumbers.Dual{Float64})
  You may have intended to import Base.erf
  Closest candidates are:
    erf(::Complex{Float32}) at /home/travis/.julia/v0.7/SpecialFunctions/src/erf.jl:26
    erf(::Complex{Float64}) at /home/travis/.julia/v0.7/SpecialFunctions/src/erf.jl:25
    erf(::BigFloat) at /home/travis/.julia/v0.7/SpecialFunctions/src/erf.jl:14

the julia version is the following:
Julia Version 0.7.0-DEV.1063
on the previous version of julia-nightly i had no problem

**Comment by ararslan** [comment]
Fixed by #65.
