### ISSUE TITLE
Odd behavior: `sparse(M::Array{Dual{Float64}})` zeroes dual values 

### ISSUE THREAD

**Issue by briochemc** [JuliaDiff/DualNumbers.jl#70]
I have no idea why this is happening, and it took me a long time to figure out that this was my issue in my application... Anyway I thought I should report it: I think calling `sparse` on a full dual-valued matrix "kills" the dual parts of the elements with no real part. MWE:
```julia
julia> M = zeros(2,2) + ones(2,2) * ε
2×2 Array{Dual{Float64},2}:
 0.0+1.0ɛ  0.0+1.0ɛ
 0.0+1.0ɛ  0.0+1.0ɛ

julia> sparse(M)
2×2 SparseMatrixCSC{Dual{Float64},Int64} with 0 stored entries
```
What's going on here? Am I missing something?

**Comment by KristofferC** [comment]
```
julia> iszero(ForwardDiff.Dual(0.0, 1.0))
true
```

**Comment by briochemc** [comment]
Yes I just figured that out
